#!/bin/bash

fileList=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(js|vue)$')

if [ ${#fileList} -gt 0 ]; then
    npx eslint ${fileList[*]} "$@"

    if [ $? -ne 0 ]; then
        echo -e "\nPlease fix the above linting issues before committing.\n"
        exit 1
    fi
fi
