#!/bin/sh
function check_for_flag {
    if git rev-parse --verify HEAD >/dev/null 2>&1
    then
        against=HEAD
    else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
    fi

    # The special marker tag to mark things which we still need to change
    marker="DO NOT PUSH"

    # Redirect output to stderr.
    exec 1>&2

    if test $(git grep "$marker" | wc -c) != 0 
    then
        cat <<\EOF
        Error: DO NOT PUSH this branch until sensitive info is removed!!!!:
EOF
        echo `git grep "$marker"`
        exit 1
    fi
}

case "${1}" in
    --about )
        echo "Check for DO NOT PUSH flag in repo and prevent pushes when present."
        ;;
    * )
        check_for_flag 
        ;;
esac


